project:
  type: website
  output-dir: docs

website:
  title: "Re-enchantment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: The Project
      - href: peatlands.qmd
        text: Peatlands and Torbiere
      - href: languagecology.qmd
        text: Language as Ecology
      - href: blog.qmd
        text: Blog and News
      - href: outputs.qmd
        text: Project Outputs
  page-footer:
    left: 
    - text: "A research project funded by the Government of Ireland Postdoctoral Fellowship Programme. Hosted at University College Dublin. &copy; 2026 Re-enchanting Peatlands"
    right:
    - text: "<img src='files/RILogo.png' alt='Research Ireland' height='30'>"

format:
  html:
    theme:
      - brite.scss
      - brand
    css: styles.css
    toc: true
    include-before-body: partials/wallpaper.html

    



