---
title: "Five weeks in"
description: "London, Donegal, bog safaris, Irish lessons, and reflections from the first five weeks of Re-enchantment."
date: 2026-10-07
categories:
  - Field notes
  - Peatlands
  - Language
---

::: {.post-kicker}
FIELD NOTES · 7 OCTOBER 2026
:::

::: {.post-opening}
Five weeks into Re-enchantment: from conversations in London to bogs in Donegal, archival research, Irish lessons, and some thoughts on where it is all beginning to lead.
:::

---

It’s Wednesday 7th October 2026, and that means it’s already been over a month since I officially started working on this fellowship. I’ll spare you the usual cliché of “time flies” and all that, although I won’t hide that it’s pretty much the mental soundtrack I’ve been playing to myself every time I notice the date on the calendar.

This is my first blog post – not just for this website or this project: it’s my first ever blog post, and I sense a feeling of uncertainty as I type these words, wondering what my blog-post voice sounds like. I’ll get there, I’m sure.

These five weeks have been nothing short of a whirlwind of excitement and trepidation. Spontaneity could be seen as the signature shade in a palette of gushy rusts, volatile blues, and intrepid greens, on a live canvas now busy with energy and dreams.

Of all places, London is where it all started. I was there to attend and present at the [RGS-IBG Annual International Conference](https://www.rgs.org/research/annual-international-conference), in a panel dedicated to “Geographies of Language and the Languages of Geography Revisited”. This is where I realised how much I feel at home when I’m surrounded by human geographers, but also how surprised I can be by just how different their approaches are. Contributions on multilingualism through a placemaking perspective, literary and translation takes on what a geography of language entails, and historical tracings of words across languages that make or break the image of a place were among the fascinating talks in the session.

It was probably one of the most enjoyable conferences I’ve attended from a networking point of view. In a short amount of time, I got to know colleagues based at the University of Manchester and the University of Bologna, and I’m now looking forward to continuing these conversations next month by visiting the Geography department at UNIBO. More to come!

In an unexpected turn of events – and a fantastic one at that – in the third week of September I visited Ulster with Prof Stefania Tufi – from PhD supervisor, via Principal Investigator of my [second postdoc](https://www.liverpool.ac.uk/languages-cultures-and-film/research/projects/borderscapes/), to now a dear colleague and trusted friend. Stefania and I booked ourselves onto the one and only [bog safari](https://solasireland.com/tours/bog-safari/) available in Ulster (perhaps even Ireland?). Led by Sharon, we had the privilege of walking through her childhood bog under the windy sun of Buncrana, hearing all about turf cutting, bog bodies, sphagnum, bog oak, and the ruthless methods of turf excavation happening in some places, leaving visible scars in these fossilised landscapes (to paraphrase Nobel Prize-winning Irish poet Seamus Heaney).

There’s way too much I could say about this surreal experience, and I can’t wait to put it all into words. For the time being, I wouldn’t hesitate to recommend [Sharon’s bog safari](https://solasireland.com/tours/bog-safari/) to anyone interested in understanding bogs first-hand.

While it was a short visit, we managed to pack in a lot of activities. As well as visiting [Glenveagh National Park](https://www.nationalparks.ie/glenveagh/) and the beautiful Atlantic coast in Gweedore, we stopped at [Caifé Kittie](https://govisitdonegal.com/places-to-eat/caife-kitty/), where the owners truly touched us with how welcoming they were. We were even able to drink some locally made bog bean – if this isn’t getting to know the bog intimately, then I don’t know what is…

The full schedule did mean that we had to miss out on the Irish music festival, [Doarn Sar Aer 2026](https://share.google/TpyPyvpXl4QmtbWO6), that was on that weekend. We heard that the Irish president was there, and the festival made the national news. I’m counting on visiting again many more times and on attending the festival next year.

Back home, I’ve kept busy starting my archival research on [Dúchas](https://www.duchas.ie/), reaching out to similar archives for Emilian, and testing the waters with potential schools and organisations in Donegal and Modena that might take part in the project. Some things are moving more quickly than others, and I’ll be able to share more in due time.

In the meantime, I started the month of October with Irish lessons. I should be able to introduce myself, but don’t test me just yet. After speaking with Tiber (Dr Tiber Falzett), my fabulous mentor, I was convinced to include this learning journey in my project, and I’ll be reporting on how learning Irish helps me understand the research – and myself – in different ways.

These weeks have also helped me understand something else. Now that I am working on this project, I have time to read and think about its themes more profoundly. This space for reflection has allowed me to see that the more I read about peatlands and language revitalisation, the more I understand just how much is already happening – and how wonderful it is to be doing this work, entangled in this mesh of trajectories: movement that seems to be heading towards a shared objective, where reconnection happens as a multispecies effort.

I feel reinvigorated and grateful for the people I know, those I’ve met, and those who will hopefully benefit from the work that we’re doing.